language: java
arch:
  - amd64
  - ppc64le
jdk:
  - openjdk11
  - openjdk15

dist: trusty

# No need for preliminary install step.
install: true
#
# Run all integration tests.
script: 
  - "mvn --show-version --errors --batch-mode clean verify"
#
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
